name: Deploy Todo App

on:
  push:
    branches:
      - Develop  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        sudo docker build . -t todo-app

    - name: Run Docker container
      run: |
        sudo docker run -d -p 8001:8001 todo-app
